### ISSUE TITLE
How to reduce the number of masks

### ISSUE THREAD

**Issue by hkdsc** [gtangg12/samesh#2]
Thanks for your excellent work. I want to ask if the mesh is over segmented, how can I adjust the model parameters to reduce the number of masks?

**Comment by gtangg12** [comment]
Hi, you can reduce
`connections_bin_threshold_percentage`
so more edges are considered in the community detection. In addition, you can explore coarser SAM grids as well as other parameters in SAM2's AutomaticMaskGenerator. If you are looking to extend the algorithm for scenes, I'd recommend using GroundedSAM (RAM -> GroundingDino -> SAM2) as a frontend instead of SAM2.

**Comment by gtangg12** [comment]
As an interesting, thought this paper fine tunes SAM's decoder to get good part segmentation. Perhaps you'd want to integrate this version of SAM for SAMesh.

https://arxiv.org/pdf/2406.08474

Please let me know if you proceed on this!
